default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tekumemo_development
  username: postgres
  password: password
  host: <%= ENV['DATABASE_HOST'] || '127.0.0.1' %>
  port: 5432

test:
  <<: *default
  database: tekumemo_test<%= ENV['TEST_ENV_NUMBER'] %>
  username: postgres
  password: password
  host: <%= ENV['DATABASE_HOST'] || '127.0.0.1' %>
  port: 5432

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  cache:
    <<: *primary_production
    # Solid Cache用の設定（プライマリと同じDBを使用）
