default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tekumemo_development
  username: postgres
  password: password
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>  # 環境変数で切り替え 理解不足なのであとで調べる
  port: 5432

test:
  <<: *default
  database: tekumemo_test
  username: postgres
  password: password
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>  # 環境変数で切り替え 理解不足なのであとで調べる
  port: 5432

production:
  url: <%= ENV['DATABASE_URL'] %>
